// <auto-generated />
namespace AppIdentity.Samples.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Modificaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201709271714212_Modificaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
